factura:
    path:     /
    defaults: { _controller: "PepeBundle:factura:index" }

factura_show:
    path:     /{id}/show
    defaults: { _controller: "PepeBundle:factura:show" }

factura_new:
    path:     /new
    defaults: { _controller: "PepeBundle:factura:new" }

factura_create:
    path:     /create
    defaults: { _controller: "PepeBundle:factura:create" }
    requirements: { _method: post }

factura_edit:
    path:     /{id}/edit
    defaults: { _controller: "PepeBundle:factura:edit" }

factura_update:
    path:     /{id}/update
    defaults: { _controller: "PepeBundle:factura:update" }
    requirements: { _method: post|put }

factura_delete:
    path:     /{id}/delete
    defaults: { _controller: "PepeBundle:factura:delete" }
    requirements: { _method: post|delete }
