localidad:
    path:     /
    defaults: { _controller: "PepeBundle:localidad:index" }

localidad_show:
    path:     /{id}/show
    defaults: { _controller: "PepeBundle:localidad:show" }

localidad_new:
    path:     /new
    defaults: { _controller: "PepeBundle:localidad:new" }

localidad_create:
    path:     /create
    defaults: { _controller: "PepeBundle:localidad:create" }
    requirements: { _method: post }

localidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "PepeBundle:localidad:edit" }

localidad_update:
    path:     /{id}/update
    defaults: { _controller: "PepeBundle:localidad:update" }
    requirements: { _method: post|put }

localidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "PepeBundle:localidad:delete" }
    requirements: { _method: post|delete }
seleccionar_localidad:
    pattern: /seleccionar
    defaults: { _controller: 'PepeBundle:Localidad:seleccionar' }
