<?php

namespace Pepe\PepeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * provinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class localidadRepository extends EntityRepository {

    public function findByTerm($term) {
        $query = $this->getEntityManager()->createQuery("
SELECT localidad.id as id, localidad.descripcion as descripcion
FROM PepeBundle:Localidad localidad
WHERE localidad.descripcion LIKE :term
")->setParameter('term', '%' . $term . '%');
        return $query->getArrayResult();
    }

    public function findByProvinciaId($provincia_id) {
        $query = $this->getEntityManager()->createQuery("
SELECT localidad
FROM PepeBundle:Localidad localidad
LEFT JOIN localidad.provincia provincia
WHERE provincia.id = :provincia_id
")->setParameter('provincia_id', $provincia_id);
        return $query->getArrayResult();
    }

}
