<?php

namespace Pepe\PepeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * provinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productoRepository extends EntityRepository {

    

}
