<?php

namespace Pepe\PepeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * provinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class provinciaRepository extends EntityRepository {

    public function findByLocalidadId($localidad_id) {
        $query = $this->getEntityManager()->createQuery("
SELECT provincia
FROM PepeBundle:Provincia provincia
LEFT JOIN provincia.localidad localidades
WHERE localidad.id = :localidad_id
")->setParameter('localidad_id', $localidad_id);
        return $query->getResult();
    }

}
